Feature/136 modify auto field using variable name
akvo/akvo-react-form pull request #137
Opened 2024-02-27 09:54 UTC by ifirmawan

2024-02-28 12:33 UTC, dedenbangkit requested changes
remove labelText and use label || name directly
```bash
src/fields/TypeText.jsx
24:  const labelText = label || name;
32:          content={labelText}

src/fields/TypeOption.jsx
57:  const labelText = label || name;
120:          content={labelText}

src/fields/TypeTable.jsx
23:  const labelText = label || name;
51:            content={labelText}

src/fields/TypeCascade.jsx
248:  const labelText = label || name;
303:        name={labelText}
327:          content={labelText}

src/fields/TypeTree.jsx
64:  const labelText = label || name;
71:          content={labelText}

src/fields/TypeNumber.jsx
42:  const labelText = label || name;
87:          content={labelText}

src/fields/TypeMultipleOption.jsx
44:  const labelText = label || name;
88:          content={labelText}

src/fields/TypeDate.jsx
29:  const labelText = label || name;
65:          content={labelText}

src/fields/TypeImage.jsx
62:  const labelText = label || name;
89:            content={labelText}

src/fields/TypeAutoField.jsx
226:  const labelText = label || name;
243:          content={labelText}

src/fields/TypeInput.jsx
32:  const labelText = label || name;
63:          content={labelText}

src/fields/TypeGeo.jsx
27:  const labelText = label || name;
36:            content={labelText}
```

2024-02-28 12:33 UTC, dedenbangkit commented on src/fields/TypeMultipleOption.jsx
> +    const _options = [...option, ...extraOption].map((o) => ({
...option.map, ...extraOption

2024-02-28 12:33 UTC, dedenbangkit commented on src/fields/TypeMultipleOption.jsx
> +  const labelText = label || name;
remove labelText

2024-02-28 12:33 UTC, dedenbangkit commented on src/fields/TypeInput.jsx
> +  const labelText = label || name;
remove labelText

2024-02-28 14:01 UTC, ifirmawan commented
> remove labelText and use label || name directly
> 
> ```shell
> src/fields/TypeText.jsx
> 24:  const labelText = label || name;
> 32:          content={labelText}
> 
> src/fields/TypeOption.jsx
> 57:  const labelText = label || name;
> 120:          content={labelText}
> 
> src/fields/TypeTable.jsx
> 23:  const labelText = label || name;
> 51:            content={labelText}
> 
> src/fields/TypeCascade.jsx
> 248:  const labelText = label || name;
> 303:        name={labelText}
> 327:          content={labelText}
> 
> src/fields/TypeTree.jsx
> 64:  const labelText = label || name;
> 71:          content={labelText}
> 
> src/fields/TypeNumber.jsx
> 42:  const labelText = label || name;
> 87:          content={labelText}
> 
> src/fields/TypeMultipleOption.jsx
> 44:  const labelText = label || name;
> 88:          content={labelText}
> 
> src/fields/TypeDate.jsx
> 29:  const labelText = label || name;
> 65:          content={labelText}
> 
> src/fields/TypeImage.jsx
> 62:  const labelText = label || name;
> 89:            content={labelText}
> 
> src/fields/TypeAutoField.jsx
> 226:  const labelText = label || name;
> 243:          content={labelText}
> 
> src/fields/TypeInput.jsx
> 32:  const labelText = label || name;
> 63:          content={labelText}
> 
> src/fields/TypeGeo.jsx
> 27:  const labelText = label || name;
> 36:            content={labelText}
> ```

Done

2024-02-29 00:00 UTC, dedenbangkit approved these changes

2024-02-29 00:00 UTC, merged